root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server-linux-amd64 ./cmd/server"
bin = "tmp/server-linux-amd64"
full_bin = "./tmp/server-linux-amd64"
include_ext = ["go", "tpl"]
exclude_dir = ["docker/db", "scripts/migrations", "tmp"]
exclude_unchanged = true
log = "air.log"
delay = 1000
stop_on_error = true
send_interrupt = false

[log]
time = false

[misc]
clean_on_exit = true
