version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: "docker/Dockerfile"
      args:
        PORT: ${PORT}
    command: sh -c "envsubst < ./dbconfig.yml.tpl > ./dbconfig.yml && ./third_party/bin/air -c air.toml"
    container_name: go-api-practice-app
    environment:
      ENV: ${ENV}
      PORT: ${PORT}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: ${MYSQL_HOST}
    expose:
      - ${PORT}
    links:
      - db
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ../:/app/
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    command: |
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    container_name: ${MYSQL_HOST}
