version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: "docker/Dockerfile"
      args:
        APP_PORT: ${APP_PORT}
    command: >
      sh -c "
      envsubst < ./dbconfig.yml.tpl > ./dbconfig.yml &&
      envsubst < ./sqlboiler.yml.tpl > ./sqlboiler.yml &&
      ./third_party/bin/air -c air.toml"
    container_name: go-api-practice-app
    environment:
      ENV: ${ENV}
      APP_PORT: ${APP_PORT}
      DB_NAME: ${MYSQL_DATABASE}_${ENV}
      DB_USER: ${MYSQL_USER}
      DB_PASS: ${MYSQL_PASSWORD}
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: ${MYSQL_PORT}
    expose:
      - ${APP_PORT}
    links:
      - db
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ../:/app/
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}_${ENV}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    command: |
      mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    container_name: ${MYSQL_HOST}
